---
title: "Analysis"
author: "Dingyi Li"
date: "4/14/2021"
output:
  pdf_document: default
  html_document: default
---
# Multiple Linear Regression
## Data preview
### Read in data
```{r}
dt = read.csv("data&figures/dt.csv")
summary(dt)
```

### Correlation Check
#### Education parameters
```{r}
cor(scale(as.matrix(dt[,c(7,8,9,10)])))
```
### Histogram
```{r}
library(ggpubr)
a<-ggdensity(dt, x = "Unemployment_Rate", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
b<-ggdensity(dt, x = "Population", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
c<-ggdensity(dt, x = "Poverty_Percentage", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
d<-ggdensity(dt, x = "Personal_Income", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
e<-ggdensity(dt, x = "HPI", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
f<-ggdensity(dt, x = "SomeCollege", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
g<-ggdensity(dt, x = "BachelorAndHigher", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
ggarrange(a,b,c,d,e,f,g, ncol = 2, nrow = 4)
```
### Histogram for logtransformation
```{r}
temp=dt
temp$HPI <- log(dt$HPI)
temp$Personal_Income <- log(dt$Personal_Income)
temp$Poverty_Percentage <- log(dt$Poverty_Percentage)
temp$Population <- log(dt$Population)
temp$HighSchoolLess <- log(dt$HighSchoolLess)
temp$BachelorAndHigher <- log(dt$BachelorAndHigher)
temp$Unemployment_Rate <- log(dt$Unemployment_Rate)
```

```{r}
library(ggpubr)
a<-ggdensity(temp, x = "Unemployment_Rate", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
b<-ggdensity(temp, x = "Population", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
c<-ggdensity(temp, x = "Poverty_Percentage", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
d<-ggdensity(temp, x = "Personal_Income", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
e<-ggdensity(temp, x = "HPI", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
f<-ggdensity(temp, x = "SomeCollege", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
g<-ggdensity(temp, x = "BachelorAndHigher", fill = "lightgray") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
ggarrange(a,b,c,d,e,f,g, ncol = 2, nrow = 4)
```

## Model fitting
```{r}
m1 = lm(log(dt$HPI)~log(dt$Personal_Income)+log(dt$Poverty_Percentage)+log(dt$Unemployment_Rate)+log(dt$Population)+dt$SomeCollege+log(dt$BachelorAndHigher))
summary(m1)
```
## Diagnostic Plots
```{r}
plot(m1)
```

```{r}
car::vif(m1)
```

## correlation plot
```{r, fig.dim = c(12,6)}
library(dplyr)
library(corrplot)
df <- dt %>% dplyr::select(HighSchoolLess:BachelorAndHigher)
res <- cor(df)

corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

# pca presentation
```{r}
library("tidymodels")
library(tidyverse)
pca_rec <- recipe(HPI ~., data = temp) %>%
  update_role(State, County, new_role = "id") %>%
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors(), id = "pca")

pca_prep <- prep(pca_rec)
tidied_pca <- tidy(pca_prep, id="pca") # extract mean values

pca_variances <- tidy(pca_prep, id = "pca", type = "variance")
pca_variances %>%
  filter(terms == "percent variance") %>%
  ggplot(aes(component, value)) +
  geom_col() +
  labs(x = "Principal Components", y = "Variance explained (%)") +
  theme_minimal()

tidied_pca %>%
  filter(component %in% str_c("PC", 1:2)) %>%
  mutate(terms = reorder_within(terms, abs(value), component), 
         component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1, scales = "free_y") +
  scale_y_reordered() +
  labs(y = NULL) +
  theme_minimal()
```


```{r}
juice(pca_prep) %>%
  ggplot(aes(PC1, PC2, label = County)) +
  geom_point(aes(color = State), alpha = 0.7, size = 2) +
  geom_text(check_overlap = TRUE, hjust = "inward") +
  labs(color = NULL) +
  theme_minimal()
```

## Collinearity Check
```{r}
car::vif(m1)
```


